sudo: false
language: go
go:
- 1.7.3
branches:
  except:
  - "/^v\\d+[.]\\d+[.]\\d+.*/"
before_install:
- openssl aes-256-cbc -K $encrypted_f5d43f9eb2f8_key -iv $encrypted_f5d43f9eb2f8_iv
  -in trtest.enc -out trtest -d
script:
- make ci-trigger
